default-resources: 
  slurm_partition: <your-slurm-partition>
  runtime: '1h'
  mem_mb: 2000


set-resources:
  filter:
    mem_mb: 24000
  gbif_match:
    mem_mb: 4000
    runtime: '6h'
  fill_missing:
    mem_mb: 4000
  fix_nonunique:
    mem_mb: 24000
  calculate_consensus:
    mem_mb: 16000
    runtime: "2h"
  batch_multi_record_bins:
    runtime: "2h"
  vsearch:
    runtime: "10h"
    mem_mb: 8000
  collect_vsearch:
    mem_mb: 4000
  stats:
    mem_mb: 4000
  format:
    mem_mb: 4000
    runtime: '12h'
  generate_kv_file:
    mem_mb: 4000
  format_qiime2:
    mem_mb: 24000

set-threads:
  filter: 10
  gbif_match: 10
  batch_multi_record_bins: 4
  fix_nonunique: 10
  calculate_consensus: 10
  format: 4
  format_qiime2: 4

printshellcmds: False
local-cores: 1
keep-going: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm