import polars as pl
import pandas as pd
import string
import gzip as gz
from tempfile import NamedTemporaryFile
from snakemake.utils import validate
import os
import sys

# set default compute account when account is None
if config["account"] is None:
    config["account"] = "None"


localrules:
    extract_input,
    gzip,
    collect_vsearch,
    concat_timestamps,


wildcard_constraints:
    n="gbif|coidb",
    suffix="tsv|fasta",
    format="sintax|dada2.toGenus|dada2.toSpecies|dada2.addSpecies",
    consensus_type="coidb|gbif.species-complete|gbif.complete",
    tool="sintax|dada2",
    s="inclNA|exclNA",


def all_input(wildcards):
    input = expand(
        "{output_dir}/{f}",
        output_dir=config["output_dir"],
        f=["coidb.info.tsv.gz", "timestamps.txt"],
    )
    input += expand(
        "{output_dir}/coidb.stats.{s}.txt",
        output_dir=config["output_dir"],
        s=["exclNA", "inclNA"],
    )
    input += expand(
        "{output_dir}/coidb.BOLD_BIN.consensus_taxonomy.{s}.tsv.gz",
        output_dir=config["output_dir"],
        s=["exclNA", "inclNA"],
    )
    input += expand(
        "{output_dir}/dada2/coidb.dada2.{t}.{s}.fasta.gz",
        output_dir=config["output_dir"],
        t=["toGenus", "toSpecies", "addSpecies"],
        s=["exclNA", "inclNA"],
    )
    input += expand(
        "{output_dir}/sintax/coidb.sintax.{s}.fasta.gz",
        output_dir=config["output_dir"],
        s=["exclNA", "inclNA"],
    )
    input += expand(
        "{output_dir}/qiime2/coidb.qiime2.info.{s}.tsv.gz",
        output_dir=config["output_dir"],
        s=["exclNA", "inclNA"],
    )
    if config["gbif_backbone"]:
        input += expand(
            "{output_dir}/{f}",
            output_dir=config["output_dir"],
            f=["backbone.info.tsv.gz"],
        )
    return input


rule all:
    input:
        all_input,


rule gzip:
    input:
        "{f}.{suffix}",
    output:
        "{f}.{suffix}.gz",
    message:
        "Compressing {wildcards.f}.{wildcards.suffix}"
    shell:
        """
        gzip -c {input} > {output}
        """


# This checkpoint extracts the input tarball (if specified).
checkpoint extract_input:
    input:
        tarball=config["input_file"],
    output:
        directory(os.path.join(config["temp_dir"], "_extract")),
    log:
        os.path.join(config["output_dir"], "_logs/extract_input.log"),
    message:
        "Extracting input file {config[input_file]}"
    shell:
        """
        rm -rf {output}
        mkdir -p {output}
        tar -C {output} -xvf {input.tarball} > {log} 2>&1
        """


def get_extracted(wildcards):
    """
    This function identifies the filename of the *.tsv file contained in the
    input tarball.
    """
    if config["input_file"].endswith(".tar.gz"):
        checkpoint_output = checkpoints.extract_input.get(**wildcards).output[0]
        tsv = expand(
            "{temp_dir}/_extract/{f}.tsv",
            f=glob_wildcards(os.path.join(checkpoint_output, "{f}.tsv")).f,
            temp_dir=config["temp_dir"],
        )
    elif config["input_file"].endswith(".tsv"):
        tsv = config["input_file"]
    return tsv


# This rule filters the input data by:
# 1. Selecting a subset of columns
# 2. Only keeping records matching COI-5P as 'marker_code'
# 3. Only keeping records with an assigned BOLD BIN
# 4. Only keeping records with a sequence length >= min_len (default 500)
# 5. Strips leading and trailing '-' characters
# 6. Removes sequences with with remaining gaps
# 7. Removes sequences with non DNA characters
# For prokaryotic records lines are kept in step 3 even if no BOLD BIN is
# assigned.
rule filter:
    input:
        tsv=get_extracted,
    output:
        tsv=temp(os.path.join(config["temp_dir"], "_processed/data.filtered.tsv")),
        timestamp=temp(
            expand("{output_dir}/input_timestamp.txt", output_dir=config["output_dir"])
        ),
    log:
        os.path.join(config["output_dir"], "_logs/filter.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    params:
        min_len=config["min_len"],
        input_file=config["input_file"],
    message:
        "Filter data to only include BOLD BIN records, trim and remove spurious sequences"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        echo "Input data:" >> {output.timestamp}
        echo "  - filename: {params.input_file}" >> {output.timestamp}
        echo "  - extracted filename: {input.tsv}" >> {output.timestamp}
        filter-records -i {input.tsv} -o {output.tsv} -l {params.min_len} 2>{log}
        """


# This rules matches species names from BOLD to species names in Catalog of Life
rule col_match:
    input:
        tsv=rules.filter.output.tsv,
    output:
        tsv=temp(
            os.path.join(config["temp_dir"], "catalog_of_life/species-matched.tsv")
        ),
        tsv_unrefined=temp(
            os.path.join(config["temp_dir"], "catalog_of_life/species-matched.raw.tsv")
        ),
    log:
        os.path.join(config["output_dir"], "_logs/col_match.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    message:
        "Matching BOLD species names to Catalog of Life"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        match-names -i {input.tsv} -c species -p {threads} --unrefined_out {output.tsv_unrefined} -o {output.tsv} > {log} 2>&1
        """


def fill_missing_input(wildcards):
    if wildcards.n == "coidb":
        return rules.filter.output.tsv
    elif wildcards.n == "col":
        return rules.col_match.output.tsv


# This rule fills in missing ranks in taxonomic dataframes.
rule fill_missing:
    input:
        fill_missing_input,
    output:
        tsv=temp(os.path.join(config["temp_dir"], "{n}.info.fill-missing.tsv")),
    log:
        os.path.join(config["output_dir"], "_logs/fill_missing.{n}.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    message:
        "Filling missing ranks for {wildcards.n} data"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        fill-missing -i {input} -o {output.tsv} 2>{log}
        """


# This rule identifies non-unique lineages and fixes these by prefixing taxa
# with parent ranks.
rule fix_nonunique:
    input:
        tsv=rules.fill_missing.output.tsv,
    output:
        tsv=temp(os.path.join(config["output_dir"], "{n}.info.tsv")),
    log:
        os.path.join(config["output_dir"], "_logs/fix_nonunique.{n}.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    params:
        id_col=lambda wildcards: "name" if wildcards.n == "col" else "bin_uri",
    message:
        "Fixing non-unique lineages for {wildcards.n}"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        fix-nonunique-lineages -i {input.tsv} --id_col {params.id_col} -o {output.tsv} 2>{log}
        """


# Update names in coidb.info.tsv based on matched species names in Catalog of
# Life.
rule consolidate_names:
    input:
        coidb=os.path.join(config["output_dir"], "coidb.info.tsv"),
        col=os.path.join(config["output_dir"], "col.info.tsv"),
    output:
        tsv=os.path.join(config["output_dir"], "coidb.info.consolidated.tsv"),
    message:
        "Consolidating taxonomy based on Catalog of Life matches"
    shell:
        """
        consolidate-names -i {input.coidb} -I {input}
        """


def consensus_input(wildcards):
    """
    Feeds input files to calculate_consensus rule.

    If --gbif-backbone command line parameter is used, the GBIF backbone files
    is also passed.
    """
    input = {}
    input["tsv"] = os.path.join(config["output_dir"], "coidb.info.tsv")
    if config["gbif_backbone"]:
        input["backbone"] = (os.path.join(config["output_dir"], "backbone.info.tsv"),)
    return input


# This rule calculates a consensus taxonomy for BOLD BINs. It uses as input
# both the BOLD data and the GBIF backbone. If BINs are present in the
# backbone this information takes precedence.
rule calculate_consensus:
    input:
        unpack(consensus_input),
    output:
        tsv=temp(
            os.path.join(
                config["output_dir"], "coidb.BOLD_BIN.consensus_taxonomy.{s}.tsv"
            )
        ),
    log:
        os.path.join(config["output_dir"], "_logs/calculate_consensus.{s}.log"),
    threads: 1
    resources:
        slurm_account=config["account"],
    params:
        threshold=config["consensus_threshold"],
        ranks=config["ranks"],
        method=config["consensus_method"],
        bb=lambda wildcards, input: (
            f"-u {input.backbone} --write_existing {config['output_dir']}/coidb.BOLD_BIN.consensus_taxonomy.from-backbone.{wildcards.s}.tsv"
            if config["gbif_backbone"]
            else ""
        ),
        exclude_missing=lambda wildcards: (
            "--exclude_missing_data" if wildcards.s == "exclNA" else ""
        ),
    message:
        "Calculating consensus taxonomy for BINs"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        consensus-taxonomy -i {input.tsv} -o {output.tsv} \
            {params.bb} -r {params.ranks} -m {params.method} \
            {params.exclude_missing} -t {params.threshold} -p {threads} 2>{log}
        """


# BINs with more than 1 record are subject to clustering with vsearch. This
# checkpoint identifies all such BINs and prepares input for vsearch
# clustering. To avoid too large workflow graph, the BINs are grouped into
# batches with the batch size determined by the '--batch-size' command line
# argument.
checkpoint batch_multi_record_bins:
    input:
        tsv=os.path.join(config["output_dir"], "coidb.info.tsv"),
    output:
        directory(os.path.join(config["temp_dir"], "_batch")),
    log:
        os.path.join(config["output_dir"], "_logs/batch_multi_record_bins.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    params:
        batch_size=config["batch_size"],
    shell:
        """
        exec &>{log}
        export POLARS_MAX_THREADS={threads}
        batch-split-bins -i {input.tsv} -o {output} -b {params.batch_size}
        ls {output}/*.fasta | while read f; do seqkit faidx --quiet $f; done
        """


# This rule clusters sequences for each batch of BOLD BINs.
rule vsearch:
    input:
        fasta=os.path.join(config["temp_dir"], "_batch/batch_{batch_id}.fasta"),
    output:
        fasta=temp(
            expand(
                "{tempdir}/_vsearch/batch_{{batch_id}}.fasta",
                tempdir=config["temp_dir"],
            )
        ),
    log:
        expand(
            "{output_dir}/_logs/vsearch_logs/batch_{{batch_id}}.log",
            output_dir=config["output_dir"],
        ),
    shadow:
        "minimal"
    threads: 1
    resources:
        slurm_account=config["account"],
    params:
        id=config["vsearch_identity"],
    message:
        "Clustering sequences in batch_{wildcards.batch_id}"
    shell:
        """
        exec &>{log}
        seqkit split \
            --by-id-prefix batch_{wildcards.batch_id}. \
            -O . -i --id-regexp "bin_uri:(BOLD:[A-Z0-9]+)" {input.fasta}
        for f in batch_{wildcards.batch_id}.*.fasta; 
        do 
            vsearch --cluster_fast $f --id {params.id} --centroids $f.centroids --threads {threads}
            rm $f
            cat $f.centroids | seqkit replace -p "\\|" -r " " >> {wildcards.batch_id}.fasta
        done
        mv {wildcards.batch_id}.fasta {output.fasta}
        """


def get_vsearch_fastas(wildcards):
    """
    This function globs all the 'batch_id' wildcards from the fasta files in the
    checkpoint_output directory.
    """
    checkpoint_output = checkpoints.batch_multi_record_bins.get(**wildcards).output[0]
    return expand(
        "{tempdir}/_vsearch/batch_{batch_id}.fasta",
        batch_id=glob_wildcards(
            os.path.join(checkpoint_output, "batch_{batch_id}.fasta")
        ).batch_id,
        tempdir=config["temp_dir"],
    )


# This rule concatenates all the vsearch clustered fasta files with
# single-record BIN fastas.
rule collect_vsearch:
    input:
        fasta=get_vsearch_fastas,
        tsv=os.path.join(config["output_dir"], "coidb.info.tsv"),
    output:
        fasta=os.path.join(config["output_dir"], "coidb.clustered.fasta.gz"),
    log:
        os.path.join(config["output_dir"], "_logs/collect_vsearch.log"),
    shadow:
        "minimal"
    threads: 4
    resources:
        slurm_account=config["account"],
    message:
        "Collecting clustered and single-record BIN fastas"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        exec &>{log}
        bold2fasta -i {input.tsv} -o singles.fasta --single --low_memory
        cat {input.fasta} singles.fasta | gzip -c > {output.fasta}
        """


# Generate statistics on created database
rule stats:
    input:
        fasta=rules.collect_vsearch.output.fasta,
        tsv=os.path.join(config["output_dir"], "coidb.info.tsv.gz"),
        consensus=rules.calculate_consensus.output,
    output:
        os.path.join(config["output_dir"], "coidb.stats.{s}.txt"),
    log:
        os.path.join(config["output_dir"], "_logs/stats.{s}.log"),
    threads: 1
    resources:
        slurm_account=config["account"],
    message:
        "Generating statistics"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        coidb-stats --tsv {input.tsv} --fasta {input.fasta} --consensus {input.consensus} > {output} 2>{log}
        """


def get_kv_format(wildcards):
    if wildcards.tool == "sintax":
        return "sintax"
    elif wildcards.tool == "dada2":
        if wildcards.format == "dada2.toGenus":
            return "dada2.toGenus"
        elif wildcards.format == "dada2.toSpecies":
            return "dada2.toSpecies"
        else:
            return "dada2.addSpecies"


rule generate_kv_file:
    input:
        rules.calculate_consensus.output.tsv,
    output:
        txt=temp(os.path.join(config["output_dir"], "{tool}/coidb.{format}.{s}.txt")),
    log:
        os.path.join(
            config["output_dir"], "_logs/generate_kv_file.{tool}.{format}.{s}.txt"
        ),
    threads: 1
    resources:
        slurm_account=config["account"],
    message:
        "Generate key-value file for {wildcards.tool} ({wildcards.format} {wildcards.s})"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        coidb-format --consensus {input} --outfile {output} --format {wildcards.format} 2>{log}
        """


def get_seqkit_pattern(wildcards):
    """
    Return the proper pattern string based on the fasta file format to produce
    """
    if wildcards.tool == "sintax" or wildcards.format == "dada2.addSpecies":
        return "' (.+)$'"
    elif wildcards.tool == "dada2":
        if wildcards.format in ["dada2.toGenus", "dada2.toSpecies"]:
            return "'.+ (.+)$'"


# This rule uses key-value files to generate sintax and dada2 formatted fasta
# files with seqkit.
rule format:
    input:
        kv_file=rules.generate_kv_file.output.txt,
        fasta=rules.collect_vsearch.output.fasta,
        consensus=rules.calculate_consensus.output.tsv,
    output:
        fasta=os.path.join(config["output_dir"], "{tool}/coidb.{format}.{s}.fasta.gz"),
    log:
        os.path.join(config["output_dir"], "_logs/format_{tool}.{format}.{s}.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    params:
        pattern=lambda wildcards: get_seqkit_pattern,
        replace=lambda wildcards: (
            " {kv}" if wildcards.format == "dada2.addSpecies" else "{kv}"
        ),
    message:
        "Generate DADA2 format fasta files"
    shell:
        """
        seqkit replace -j {threads} -p {params.pattern} -r '{params.replace}' -k {input.kv_file} -o {output.fasta} {input.fasta} >{log} 2>&1
        """


# This rule formats the tsv file for use with QIIME2 via qiime tools import
# --type 'FeatureData[Taxonomy]' --input-format TSVTaxonomyFormat
rule format_qiime2:
    input:
        fasta=rules.collect_vsearch.output.fasta,
        consensus=rules.calculate_consensus.output.tsv,
    output:
        temp(os.path.join(config["output_dir"], "qiime2", "coidb.qiime2.info.{s}.tsv")),
    log:
        os.path.join(config["output_dir"], "_logs", "format_qiime2.{s}.log"),
    threads: 4
    resources:
        slurm_account=config["account"],
    message:
        "Generate QIIME2 compatible TSV file"
    shell:
        """
        export POLARS_MAX_THREADS={threads}
        coidb-format --fasta {input.fasta} --consensus {input.consensus} --format qiime2 --outfile {output} 2>{log}
        """


def timestamp_input(wildcards):
    input = [rules.filter.output.timestamp[0]]
    if config["gbif_backbone"]:
        input.append(rules.download_backbone.output.timestamp[0])
    return input


# This rule combines the timestamp files into a single file.
rule concat_timestamps:
    input:
        timestamp_input,
    output:
        os.path.join(config["output_dir"], "timestamps.txt"),
    shell:
        """
        cat {input} > {output}
        """
